/*
 * esbuild.config.mjs（打包脚本）
 * 文件作用：用 esbuild 把 TypeScript 源码打包成 Obsidian 能加载的单个 main.js。
 * 概念解释：Obsidian 插件最终运行的是 main.js，本脚本负责把 src/main.ts 及其依赖"打包/压缩"成它。
 * 用法：npm run build（带 --production 压缩）或 npm run dev（watch 监听改动热重载）。
 */

import esbuild from 'esbuild';
import process from 'process';
import fs from 'fs';

// banner：生成文件顶部的注释块，声明这是由 esbuild 自动生成的文件（提醒不要直接手改 main.js）
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// 是否生产模式：命令行带 --production 时走压缩，否则进入监听模式
const prod = process.argv.includes('--production');

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'], // 打包入口：从 main.ts 开始把依赖都收进来
  bundle: true, // bundle=true：把所有 import 合并成一个文件
  external: ['obsidian'], // external：obsidian 由 Obsidian 运行时提供，不要打进包里（减小体积、避免重复）
  format: 'cjs', // 输出 CommonJS 格式（Obsidian 加载插件用的模块格式）
  target: 'ES2018', // 目标语法级别，兼容主流环境
  logLevel: 'info',
  sourcemap: prod ? false : 'inline', // 非生产模式生成内联 sourcemap，便于调试时定位源码
  treeShaking: true, // 摇树优化：删除未被引用的无用代码
  outfile: 'main.js', // 输出文件：Obsidian 加载的就是它
  loader: {
    '.svg': 'text', // SVG 作为字符串内联，便于热力图直接插入 DOM
  },
});

if (prod) {
  // 生产模式：一次性重新构建后退出
  await context.rebuild();
  process.exit(0);
} else {
  // 开发模式：持续监听文件改动并自动重新打包（热重载）
  await context.watch();
}
