/*
 * esbuild.config.mjs（打包脚本）
 * 文件作用：用 esbuild 把 TypeScript 源码打包成 Obsidian 能加载的单个 main.js。
 * 概念解释：Obsidian 插件最终运行的是 main.js，本脚本负责把 src/main.ts 及其依赖"打包/压缩"成它。
 * 用法：npm run build（带 --production 压缩）或 npm run dev（watch 监听改动热重载）。
 */

import esbuild from 'esbuild';
import process from 'process';
import fs from 'fs';
import path from 'path';

// banner：生成文件顶部的注释块，声明这是由 esbuild 自动生成的文件（提醒不要直接手改 main.js）
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// 构建输出目录：所有产物集中到「版本」文件夹（与 finance-block 对齐）
const DIST_DIR = '版本';

// 是否生产模式：命令行带 --production 时走压缩，否则进入监听模式
const prod = process.argv.includes('--production');

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'], // 打包入口：从 main.ts 开始把依赖都收进来
  bundle: true, // bundle=true：把所有 import 合并成一个文件
  external: ['obsidian'], // external：obsidian 由 Obsidian 运行时提供，不要打进包里（减小体积、避免重复）
  format: 'cjs', // 输出 CommonJS 格式（Obsidian 加载插件用的模块格式）
  target: 'ES2018', // 目标语法级别，兼容主流环境
  logLevel: 'info',
  sourcemap: prod ? false : 'inline', // 非生产模式生成内联 sourcemap，便于调试时定位源码
  treeShaking: true, // 摇树优化：删除未被引用的无用代码
  outfile: path.join(DIST_DIR, 'main.js'), // 输出到「版本」文件夹
  loader: {
    '.svg': 'text', // SVG 作为字符串内联，便于热力图直接插入 DOM
  },
});

/** 将 manifest.json 和 styles.css 复制到「版本」文件夹，组成完整分发包 */
function copyAssets() {
  if (!fs.existsSync(DIST_DIR)) fs.mkdirSync(DIST_DIR, { recursive: true });
  for (const file of ['manifest.json', 'styles.css']) {
    fs.copyFileSync(file, path.join(DIST_DIR, file));
  }
}

/*
 * 第二构建入口：workout-block CLI（配套技能 workout-block-record 的随附脚本）。
 * 与插件共享 src/data 的纯模块（csvFormat/configMigrate/statExpr/display/codeBlockDefs），
 * 保证两侧对 CSV/配置的理解逐字节一致。platform=node 让 node 内置模块自动 external。
 */
const CLI_SKILL_DIR = path.join('workout-block-record', 'scripts');
const cliContext = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/cli/main.ts'],
  bundle: true,
  platform: 'node',
  target: 'node18',
  format: 'cjs',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: path.join(CLI_SKILL_DIR, 'workout-cli.js'),
});

// --cli：只构建 CLI（技能脚本更新时用）
if (process.argv.includes('--cli')) {
  await cliContext.rebuild();
  process.exit(0);
}

if (prod) {
  // 生产模式：一次性重新构建后退出（插件 + CLI 两个产物）
  await context.rebuild();
  await cliContext.rebuild();
  copyAssets();
  process.exit(0);
} else {
  // 开发模式：确保目录存在并复制资源，然后持续监听文件改动并自动重新打包（热重载）
  if (!fs.existsSync(DIST_DIR)) fs.mkdirSync(DIST_DIR, { recursive: true });
  copyAssets();
  // 顺手构建一次 CLI（不监听；改 CLI 源码后用 npm run build:cli 重建）
  await cliContext.rebuild();
  await context.watch();
}
